services:
  promptify:
    container_name: promptify
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host
    expose:
      - '3000'
    restart: unless-stopped
